//------------------------------------------------------------------------------
// This file is part of the QMdbSim2 project, a Microchip Simulator framework
// for QSpice C-Block components.  See the GitHub repository at
// https://github.com/robdunn4/QSpice/ for the complete project, current
// sources, documentation, and demonstration code.
//------------------------------------------------------------------------------
/*
 * This template is used by QSymGen3 to generate DLL code.
 * Revision Date:  2026.07.25
 */
// see PerfTimer.h...
#define PERFTIMER_ENABLED
// #define PERFTIMER_DISABLED

#include <MdbConfig.h>
#include <MdbSim.h>
#include <PerfTimer.h>
#include <format>
#include <functional>
#include <sstream>

// some performance timer constants
const char *PT_QsSim  = "QSpice Sim Time";     // total simulation time (approx)
const char *PT_Phase1 = "MDB Phase 1 Startup"; // mostly load Java
const char *PT_Phase2 = "MDB Phase 2 Startup"; // initialize MDB for device
const char *PT_Step   = "MDB Step Calls";      // mostly main loop MDB step time

/*
 *  QSpice declarations/definitions
 */
extern "C" __declspec(dllexport) int (*Display)(const char *format, ...) = 0;
extern "C" __declspec(dllexport) const bool *HoldICs                     = 0;
extern "C" __declspec(dllexport) const bool *ForKeeps                    = 0;

union uData {
  bool                   b;
  char                   c;
  unsigned char          uc;
  short                  s;
  unsigned short         us;
  int                    i;
  unsigned int           ui;
  float                  f;
  double                 d;
  long long int          i64;
  unsigned long long int ui64;
  char                  *str;
  unsigned char         *bytes;
};

int __stdcall DllMain(void *module, unsigned int reason, void *reserved) {
  return 1;
}

/*
 * Per-instance component data
 */
struct InstData {
  explicit InstData() {}
  ~InstData() { mdb.stopSim(); }

  MdbSim      mdb;
  std::string deviceName;
  std::string vddName;
  bool        lastClkState = 0;
  bool        simStarted   = false; // true once startSim() succeeds
  PerfTimer   pt;
};

// pointer typedef for convenience
typedef InstData *pInstData;

/*
 * global variables
 */
bool gAbortFlg = false; // for "graceful" early termination

/*
 * convenience function to display error and set up to abort simulation
 */
void SimError(pInstData inst) {
  gAbortFlg = true;
  Display(inst->mdb.getLastErrMsg());
  Display("\n");
}

/*
 * Java stdout/stderr line handlers -- forwards lines to Display() instead of
 * allowing Java to write to stdout (which isn't handled well in the timer-based
 * QSpice stdout servicing); could also be used to filter "noise" from simulator
 * output
 *
 * Note:  These functions probably belong in the shared code library rather than
 * in this device-specific template code; currently here in case we find
 * something in the simulator that is specific to a given device
 *
 * Note:  We could enable/disable suppressing simulator output at runtime using
 * QMdbCfg.ini or a per-instance attribute flag in device symbol; do we need
 * that flexibility?
 */
void HandleJavaStdoutLine(pInstData inst, const std::string &line) {
  if (line.empty()) return;
  Display("%s\n", line.c_str());
}

void HandleJavaStderrLine(pInstData inst, const std::string &line) {
  if (line.empty()) return;
  Display("%s\n", line.c_str());
}

/*
 * QSpice evaluation function
 */
extern "C" __declspec(dllexport) void atmega32(pInstData *opaque, double t,
                                               uData *data) {
  // NOTE: The input declarations below were generated by QSymGen3
  // as references rather than stack variable copies as from QSpice.
  // Manual modification is not recommended.

  double     &VCC         = data[0].d;    // input
  double     &AREF        = data[1].d;    // input
  double     &AVCC        = data[2].d;    // input
  double     &PA0_I       = data[3].d;    // input
  double     &PA1_I       = data[4].d;    // input
  double     &PA2_I       = data[5].d;    // input
  double     &PA3_I       = data[6].d;    // input
  double     &PA4_I       = data[7].d;    // input
  double     &PA5_I       = data[8].d;    // input
  double     &PA6_I       = data[9].d;    // input
  double     &PA7_I       = data[10].d;   // input
  double     &PB0_I       = data[11].d;   // input
  double     &PB1_I       = data[12].d;   // input
  double     &PB2_I       = data[13].d;   // input
  double     &PB3_I       = data[14].d;   // input
  double     &PB4_I       = data[15].d;   // input
  double     &PB5_I       = data[16].d;   // input
  double     &PB6_I       = data[17].d;   // input
  double     &PB7_I       = data[18].d;   // input
  bool       &SIMCLK      = data[19].b;   // input
  double     &PC0_I       = data[20].d;   // input
  double     &PC1_I       = data[21].d;   // input
  double     &PC2_I       = data[22].d;   // input
  double     &PC3_I       = data[23].d;   // input
  double     &PC4_I       = data[24].d;   // input
  double     &PC5_I       = data[25].d;   // input
  double     &PC6_I       = data[26].d;   // input
  double     &PC7_I       = data[27].d;   // input
  double     &PD0_I       = data[28].d;   // input
  double     &PD1_I       = data[29].d;   // input
  double     &PD2_I       = data[30].d;   // input
  double     &PD3_I       = data[31].d;   // input
  double     &PD4_I       = data[32].d;   // input
  double     &PD5_I       = data[33].d;   // input
  double     &PD6_I       = data[34].d;   // input
  double     &PD7_I       = data[35].d;   // input
  double     &RESET       = data[36].d;   // input
  double     &XTAL1       = data[37].d;   // input
  const char *DevPartName = data[38].str; // input parameter
  const char *DevPgmPath  = data[39].str; // input parameter
  const char *CfgIniPath  = data[40].str; // input parameter
  double     &PA0_O       = data[41].d;   // output
  bool       &PA0_C       = data[42].b;   // output
  double     &PA1_O       = data[43].d;   // output
  bool       &PA1_C       = data[44].b;   // output
  double     &PA2_O       = data[45].d;   // output
  bool       &PA2_C       = data[46].b;   // output
  double     &PA3_O       = data[47].d;   // output
  bool       &PA3_C       = data[48].b;   // output
  double     &PA4_O       = data[49].d;   // output
  bool       &PA4_C       = data[50].b;   // output
  double     &PA5_O       = data[51].d;   // output
  bool       &PA5_C       = data[52].b;   // output
  double     &PA6_O       = data[53].d;   // output
  bool       &PA6_C       = data[54].b;   // output
  double     &PA7_O       = data[55].d;   // output
  bool       &PA7_C       = data[56].b;   // output
  double     &PB0_O       = data[57].d;   // output
  bool       &PB0_C       = data[58].b;   // output
  double     &PB1_O       = data[59].d;   // output
  bool       &PB1_C       = data[60].b;   // output
  double     &PB2_O       = data[61].d;   // output
  bool       &PB2_C       = data[62].b;   // output
  double     &PB3_O       = data[63].d;   // output
  bool       &PB3_C       = data[64].b;   // output
  double     &PB4_O       = data[65].d;   // output
  bool       &PB4_C       = data[66].b;   // output
  double     &PB5_O       = data[67].d;   // output
  bool       &PB5_C       = data[68].b;   // output
  double     &PB6_O       = data[69].d;   // output
  bool       &PB6_C       = data[70].b;   // output
  double     &PB7_O       = data[71].d;   // output
  bool       &PB7_C       = data[72].b;   // output
  double     &PC0_O       = data[73].d;   // output
  bool       &PC0_C       = data[74].b;   // output
  double     &PC1_O       = data[75].d;   // output
  bool       &PC1_C       = data[76].b;   // output
  double     &PC2_O       = data[77].d;   // output
  bool       &PC2_C       = data[78].b;   // output
  double     &PC3_O       = data[79].d;   // output
  bool       &PC3_C       = data[80].b;   // output
  double     &PC4_O       = data[81].d;   // output
  bool       &PC4_C       = data[82].b;   // output
  double     &PC5_O       = data[83].d;   // output
  bool       &PC5_C       = data[84].b;   // output
  double     &PC6_O       = data[85].d;   // output
  bool       &PC6_C       = data[86].b;   // output
  double     &PC7_O       = data[87].d;   // output
  bool       &PC7_C       = data[88].b;   // output
  double     &PD0_O       = data[89].d;   // output
  bool       &PD0_C       = data[90].b;   // output
  double     &PD1_O       = data[91].d;   // output
  bool       &PD1_C       = data[92].b;   // output
  double     &PD2_O       = data[93].d;   // output
  bool       &PD2_C       = data[94].b;   // output
  double     &PD3_O       = data[95].d;   // output
  bool       &PD3_C       = data[96].b;   // output
  double     &PD4_O       = data[97].d;   // output
  bool       &PD4_C       = data[98].b;   // output
  double     &PD5_O       = data[99].d;   // output
  bool       &PD5_C       = data[100].b;  // output
  double     &PD6_O       = data[101].d;  // output
  bool       &PD6_C       = data[102].b;  // output
  double     &PD7_O       = data[103].d;  // output
  bool       &PD7_C       = data[104].b;  // output
  double     &XTAL2       = data[105].d;  // output

  const double &vddRef = VCC;

  // if gAbortFlg is set, we're just waiting on MaxExtStepSize() to force abort
  if (gAbortFlg) return;

  pInstData inst = *opaque;

  // ── Phase 1: allocate instance and configure paths (first call only) ──
  // Done immediately regardless of VDD or HoldICs state.  Does not start
  // the simulator -- that requires a valid VDD which QSpice may not have
  // provided yet.
  if (!inst) {
    inst = *opaque = new InstData();
    inst->pt.start(PT_QsSim);

    /*** Begin QSymGen3 Code Snippet ***/
    // resolves QSpice-downcased device name to canonical case for MDBCS
    inst->deviceName = [DevPartName]() -> std::string {
      static constexpr std::string_view deviceNames[] = {
          "ATmega32",
          "ATmega32L",
      };
      for (const auto &name : deviceNames)
        if (_stricmp(DevPartName, name.data()) == 0) return std::string(name);
      Display(std::format("Unknown device \"{}\"; check P record in pin defs.",
                          DevPartName)
                  .c_str());
      gAbortFlg = true;
      return "";
    }();

    // register pin/port/name mappings
    inst->vddName = "VCC";
    inst->mdb.addPinPortMap("AREF", &AREF);
    inst->mdb.addPinPortMap("AVCC", &AVCC);
    inst->mdb.addPinPortMap("PA0", &PA0_I, &PA0_O, &PA0_C);
    inst->mdb.addPinPortMap("PA1", &PA1_I, &PA1_O, &PA1_C);
    inst->mdb.addPinPortMap("PA2", &PA2_I, &PA2_O, &PA2_C);
    inst->mdb.addPinPortMap("PA3", &PA3_I, &PA3_O, &PA3_C);
    inst->mdb.addPinPortMap("PA4", &PA4_I, &PA4_O, &PA4_C);
    inst->mdb.addPinPortMap("PA5", &PA5_I, &PA5_O, &PA5_C);
    inst->mdb.addPinPortMap("PA6", &PA6_I, &PA6_O, &PA6_C);
    inst->mdb.addPinPortMap("PA7", &PA7_I, &PA7_O, &PA7_C);
    inst->mdb.addPinPortMap("PB0", &PB0_I, &PB0_O, &PB0_C);
    inst->mdb.addPinPortMap("PB1", &PB1_I, &PB1_O, &PB1_C);
    inst->mdb.addPinPortMap("PB2", &PB2_I, &PB2_O, &PB2_C);
    inst->mdb.addPinPortMap("PB3", &PB3_I, &PB3_O, &PB3_C);
    inst->mdb.addPinPortMap("PB4", &PB4_I, &PB4_O, &PB4_C);
    inst->mdb.addPinPortMap("PB5", &PB5_I, &PB5_O, &PB5_C);
    inst->mdb.addPinPortMap("PB6", &PB6_I, &PB6_O, &PB6_C);
    inst->mdb.addPinPortMap("PB7", &PB7_I, &PB7_O, &PB7_C);
    inst->mdb.addPinPortMap("PC0", &PC0_I, &PC0_O, &PC0_C);
    inst->mdb.addPinPortMap("PC1", &PC1_I, &PC1_O, &PC1_C);
    inst->mdb.addPinPortMap("PC2", &PC2_I, &PC2_O, &PC2_C);
    inst->mdb.addPinPortMap("PC3", &PC3_I, &PC3_O, &PC3_C);
    inst->mdb.addPinPortMap("PC4", &PC4_I, &PC4_O, &PC4_C);
    inst->mdb.addPinPortMap("PC5", &PC5_I, &PC5_O, &PC5_C);
    inst->mdb.addPinPortMap("PC6", &PC6_I, &PC6_O, &PC6_C);
    inst->mdb.addPinPortMap("PC7", &PC7_I, &PC7_O, &PC7_C);
    inst->mdb.addPinPortMap("PD0", &PD0_I, &PD0_O, &PD0_C);
    inst->mdb.addPinPortMap("PD1", &PD1_I, &PD1_O, &PD1_C);
    inst->mdb.addPinPortMap("PD2", &PD2_I, &PD2_O, &PD2_C);
    inst->mdb.addPinPortMap("PD3", &PD3_I, &PD3_O, &PD3_C);
    inst->mdb.addPinPortMap("PD4", &PD4_I, &PD4_O, &PD4_C);
    inst->mdb.addPinPortMap("PD5", &PD5_I, &PD5_O, &PD5_C);
    inst->mdb.addPinPortMap("PD6", &PD6_I, &PD6_O, &PD6_C);
    inst->mdb.addPinPortMap("PD7", &PD7_I, &PD7_O, &PD7_C);
    inst->mdb.addPinPortMap("RESET", &RESET);
    inst->mdb.addPinPortMap("XTAL1", &XTAL1);
    // TODO: output-only pin "XTAL2" -- review addPinPortMap() signature
    /*** End QSymGen3 Code Snippet ***/

    // load MdbConfig.ini from MdbSimPath ("." = DLL directory)
    MdbConfig cfg;
    if (!cfg.load(CfgIniPath)) {
      Display("MdbConfig error: %s\n", cfg.getLastErrMsg());
      SimError(inst);
      return;
    }

    // display resolved configuration paths for diagnostics
    Display("MdbConfig resolved paths:\n");
    Display("  Ini:        %s\n", cfg.getIniFile().c_str());
    Display("  MplabxRoot: %s\n", cfg.getMplabxRoot().c_str());
    Display("  JdkRoot:    %s\n", cfg.getJdkRoot().c_str());
    Display("  QMdbcsJar:  %s\n", cfg.getQMdbcsJar().c_str());
    Display("  JvmDll:     %s\n", cfg.getJvmDll().c_str());

    // build MdbSim::Config from the resolved paths and pass to MdbSim
    MdbSim::Config simCfg;
    simCfg.jvmDllPath    = cfg.getJvmDll();
    simCfg.mdbcsJar      = cfg.getQMdbcsJar();
    simCfg.mplabxRoot    = cfg.getMplabxRoot();
    simCfg.packsFolder   = cfg.getPacksFolder();
    simCfg.thirdpartyLib = cfg.getThirdparty();
    inst->pt.start(PT_Phase1);
    inst->mdb.configure(simCfg);
    inst->pt.stop(PT_Phase1);
  }

  // ── Phase 2: start simulator once QSpice VDD is valid ─────────────────
  // Deferred from Phase 1 because QSpice may supply 0V on the VDD pin
  // during early initialization calls.  VDD is read directly from the
  // QSpice pin here so the device voltage matches the actual schematic value
  // without hardcoding.
  if (!inst->simStarted) {
    if (!*ForKeeps) return; // QSpice initializing; VDD may be invalid -- wait

    // setVDD() must be called before startSim(); cannot be set/changed once
    // simulation is running; VDD name can vary by device and is set in phase 1
    // code snippet above
    if (!inst->mdb.setVDD(inst->vddName.c_str(), vddRef)) {
      SimError(inst);
      return;
    }

    // bind handlers and instance pointer to functions callable from Java
    // callback
    MdbSim::StdoutLineHandler stdoutHandler =
        std::bind(&HandleJavaStdoutLine, inst, std::placeholders::_1);
    MdbSim::StdoutLineHandler stderrHandler =
        std::bind(&HandleJavaStderrLine, inst, std::placeholders::_1);

    // start JVM, load program, connect simulator, cache pin objects
    inst->pt.start(PT_Phase2);
    if (!inst->mdb.startSim(inst->deviceName.c_str(), DevPgmPath, stdoutHandler,
                            stderrHandler)) {
      SimError(inst);
      inst->pt.stop(PT_Phase2);
      return;
    }
    inst->pt.stop(PT_Phase2);

    Display("%s / QMdbCS %s -- MDB simulator ready:\n  Device:  \"%s\"\n  "
            "Program: \"%s\"\n  VDD:     %.2fV\n",
            inst->mdb.getVerInfo(), inst->mdb.getQMdbCSVersion().c_str(),
            DevPartName, DevPgmPath, inst->mdb.getVDD());

    // get initial pin states from MDB
    if (!inst->mdb.getPinStates()) {
      SimError(inst);
      return;
    }

    // set I/O direction of tri-state ports (QSpice side)
    inst->mdb.setCtrlPorts();

    // set initial output port states (QSpice side)
    inst->mdb.setOutPorts();

    inst->simStarted = true;
  }

  /***********************************
   *** evaluation code begins here ***
   ***********************************/

  // hold off clocking while QSpice is initializing or in Trunc()
  // (don't use Trun() unless you really understand the code!)
  if (*HoldICs || !*ForKeeps) {
    inst->lastClkState = SIMCLK;
    return;
  }

  // check for falling edge of CLK
  if (inst->lastClkState == SIMCLK) return;
  inst->lastClkState = SIMCLK;
  if (SIMCLK) return;

  // timer
  PerfTimer::ScopedTimer ptStep(inst->pt, PT_Step);

  // set input pin states in MDB simulator from QSpice ports
  if (!inst->mdb.setInPins()) {
    SimError(inst);
    return;
  }

  // step MDB simulation by one machine instruction
  if (!inst->mdb.stepInst()) {
    SimError(inst);
    return;
  }

  // refresh pin states from MDB
  if (!inst->mdb.getPinStates()) {
    SimError(inst);
    return;
  }

  // set component tri-state port config from MDB
  inst->mdb.setCtrlPorts();

  // set output ports from MDB states
  inst->mdb.setOutPorts();
} // end of evaluation function

/*
 * MaxExtStepSize() -- used here to prematurely terminate simulation
 * gracefully
 */
extern "C" __declspec(dllexport) double MaxExtStepSize(pInstData inst) {
  const double forever  = 1e308;
  const double abortSim = -1e308;

  if (gAbortFlg || inst->mdb.getErrState()) {
    Display("Aborting simulation...\n");
    return abortSim;
  }

  return forever;
} // end of MaxExtStepSize()

/*
 * Destroy() -- release per-instance data
 */
extern "C" __declspec(dllexport) void Destroy(pInstData inst) {
  inst->pt.stop(PT_QsSim);

  // print performance timer info if enabled
  std::ostringstream oss;
  inst->pt.report(oss);
  if (!oss.str().empty()) Display("%s", oss.str().c_str());

  delete inst;
} // end of Destroy()
