[QMdbCfg]
;
; MPLAB X installation root.  All MPLAB X paths are derived from this.
;
MplabxRoot=C:\Program Files\Microchip\MPLABX\v6.30

;
; JdkRoot MUST point to a 32-bit JRE.
;
JdkRoot=C:\Program Files (x86)\Eclipse Adoptium\jdk-8.0.472.8-hotspot\jre
; JdkRoot=C:\Program Files (x86)\Eclipse Adoptium\jdk-17.0.17.10-hotspot

;
; Full path to qmdbcs.jar.
;
; QMdbcsJar=.\QMdbCS\qmdbcs.jar
; QMdbcsJar=C:\Dev\QSpice\Projects\QMdbSim2_Project\Java_API\mplab-x-sdk_v6.30\mdbcs\mdbcs\dist\qmdbcs.jar
QMdbcsJar=..\..\Java_API\mplab-x-sdk_v6.30\mdbcs\mdbcs\dist\qmdbcs.jar

;
; End of QMdbCfg.ini
;