[QMdbCfg]
;
; MPLAB X installation root.  All MPLAB X paths are derived from this.
;
MplabxRoot=C:\Program Files\Microchip\MPLABX\v6.30

;
; JdkRoot MUST point to a 32-bit JRE.
;
; Comparing v8 to v17:
;   v8:  0.611 ms avg per instruction step //  0.486 ms avg
;   v17: 1.586 ms avg per instruction step //  1.434 ms avg
; So v8 is 2.5x faster?  Curious, that is...
;
JdkRoot=C:\Program Files (x86)\Eclipse Adoptium\jdk-8.0.472.8-hotspot\jre
; JdkRoot=C:\Program Files (x86)\Eclipse Adoptium\jdk-17.0.17.10-hotspot

;
; Full path to qmdbcs.jar.
;
; QMdbcsJar=.\QMdbCS\qmdbcs.jar
QMdbcsJar=C:\Dev\QSpice\Projects\QMdbSim2_Project\Java_API\mplab-x-sdk_v6.30\mdbcs\mdbcs\dist\qmdbcs.jar

;
; End of QMdbCfg.ini
;