//-----------------------------------------------------------------------------
// This file is part of the the QSymGen3 command-line tool contained in the
// QParser2 project.  You can find the complete project here:
// https://github.com/robdunn4/QSpice/
//-----------------------------------------------------------------------------
#include "UDataFixup.h"
#include <cctype>
#include <string_view>

namespace {
	constexpr std::string_view kInputTag = "// input";

	// Trailing-comment must be EXACTLY "// input" -- deliberately excludes
	// "// input parameter"
	bool isExactInputLine(const std::string& line) {
		if (line.size() < kInputTag.size()) return false;
		std::string_view tail(line.data() + line.size() - kInputTag.size(),
			kInputTag.size());
		return tail == kInputTag;
	}

	// Inserts '&' immediately before the variable name
	std::string insRefOperator(const std::string& line) {
		std::size_t eqPos = line.find('=');
		if (eqPos == std::string::npos) return line;

		// walk backward from '=', skipping whitespace, to the end of whatever
		// token precedes it
		std::size_t tokenEnd = eqPos;
		while (tokenEnd > 0 &&
			(line[tokenEnd - 1] == ' ' || line[tokenEnd - 1] == '\t'))
			--tokenEnd;
		if (tokenEnd == 0) return line; // nothing before '=' at all

		// that token must end in a plain identifier character -- not, say, ']'
		// from an array subscript, which this simple insertion can't handle
		// correctly
		unsigned char lastChar = static_cast<unsigned char>(line[tokenEnd - 1]);
		if (!(std::isalnum(lastChar) || lastChar == '_')) return line;

		// walk backward through the identifier itself to find where it starts
		std::size_t identStart = tokenEnd;
		while (identStart > 0) {
			unsigned char c = static_cast<unsigned char>(line[identStart - 1]);
			if (std::isalnum(c) || c == '_') --identStart;
			else break;
		}

		// the identifier must itself be preceded by whitespace and a type token
		// -- i.e. it can't be the very first thing on the (trimmed) line
		std::size_t lineStart = line.find_first_not_of(" \t");
		if (lineStart == std::string::npos || identStart <= lineStart) return line;
		if (line[identStart - 1] != ' ' && line[identStart - 1] != '\t') return line;

		std::string out = line;
		out.insert(identStart, "&");
		return out;
	}

	const StrList& bannerLines() {
		static const StrList banner = {
			"    // NOTE: The input declarations below were generated by QSymGen3\n"
			"    // as references rather than stack variable copies as from QSpice.\n"
			"    // Manual modification is not recommended.\n"
		};
		return banner;
	}
} // namespace

StrList UDataFixup::apply(const StrList& uDataLines) {
	StrList out;
	bool    bannerEmitted = false;

	for (const std::string& line : uDataLines) {
		if (isExactInputLine(line)) {
			if (!bannerEmitted) {
				for (const std::string& b : bannerLines()) out.push_back(b);
				bannerEmitted = true;
			}
			out.push_back(insRefOperator(line));
		}
		else {
			out.push_back(line);
		}
	}

	return out;
}